print("Insert value of Bill")
bill=input()
bill=float(bill)
print("how many people?")
people=input()
tip = int(input("how much tip will you give?))
result=(bill/int(people))*(1+(tip/100))
print("price everyone will pay is %8.2f" %(result))
