bill=float(input("Insert value of Bill"))
people=int(input("how many people?"))
tip = int(input("how much tip will you give?))
result=(bill/people)*(1+(tip/100))
print("price everyone will pay is %8.2f" %(result))
